{
 "title": "Distributed Job Scheduler Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Backlog (Jobs Waiting in Redis)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jobs_queued_total) - sum(jobs_processed_total)",
     "legendFormat": "Pending Jobs"
    }
   ]
  },
  {
   "title": "Worker Throughput (Jobs Processed per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(jobs_processed_total[1m]))",
     "legendFormat": "Jobs / sec"
    }
   ]
  },
  {
   "title": "Avg Time Waiting in Queue (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jobs_queue_time_milliseconds_sum[1m])) / sum(rate(jobs_queue_time_milliseconds_count[1m]))",
     "legendFormat": "Queue Wait Time"
    }
   ]
  },
  {
   "title": "Avg Job Execution Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jobs_execution_time_milliseconds_sum[1m])) / sum(rate(jobs_execution_time_milliseconds_count[1m]))",
     "legendFormat": "Execution Time"
    }
   ]
  },
  {
   "title": "Avg Total Lifecycle Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(jobs_total_lifecycle_time_milliseconds_sum[1m])) / sum(rate(jobs_total_lifecycle_time_milliseconds_count[1m]))",
     "legendFormat": "Total Time (API to Finished)"
    }
   ]
  }
 ]
}